#!/usr/bin/env python3
"""
Generate a shell script to anonymize all DICOM files in the nsclc_immuno_cts dataset.

This script:
1. Scans the input directory for patient-study combinations
2. Assigns sequential anonymized patient IDs
3. Outputs a mapping file (MRN -> anonymized ID)
4. Generates a shell script that runs anonymize.py for each patient-study
"""

import os
import re
from pathlib import Path
from collections import defaultdict


# Input/output paths
INPUT_DIR = Path("/Users/michael/Box Sync/Michael Gensheimer's Files/research/lesion ident segment/data/lung/nsclc_immuno_cts/dicom")
OUTPUT_DIR = Path("/Users/michael/Box Sync/Michael Gensheimer's Files/research/lesion ident segment/data/lung/nsclc_immuno_cts/dicom_anonymized")
SCRIPT_OUTPUT = Path("/Users/michael/Documents/software/python/dicomrt-anonymize/run_anonymization.sh")
MAPPING_OUTPUT = Path("/Users/michael/Box Sync/Michael Gensheimer's Files/research/lesion ident segment/data/lung/nsclc_immuno_cts/mrn_to_anon_id_mapping.txt")


def find_dicom_directory(base_dir: Path) -> Path | None:
    """
    Find the deepest directory containing .dcm files.
    
    The structure is: base_dir / date__Studies / patient_name_folder / *.dcm
    """
    if not base_dir.exists():
        return None
    
    # Walk the directory tree to find .dcm files
    for root, dirs, files in os.walk(base_dir):
        dcm_files = [f for f in files if f.endswith('.dcm')]
        if dcm_files:
            return Path(root)
    
    return None


def parse_directory_name(dirname: str) -> tuple[str, int, str] | None:
    """
    Parse directory name like '10183085_1_images' or '10183085_1_rtst'.
    
    Returns: (patient_id, study_number, type) or None if not matching pattern
    """
    match = re.match(r'^(\d+)_(\d+)_(images|rtst)$', dirname)
    if match:
        return match.group(1), int(match.group(2)), match.group(3)
    return None


def main():
    # Collect all patient-study combinations
    patient_studies = defaultdict(lambda: defaultdict(dict))  # {mrn: {study_num: {type: path}}}
    
    for item in INPUT_DIR.iterdir():
        if not item.is_dir():
            continue
        
        parsed = parse_directory_name(item.name)
        if parsed is None:
            continue
        
        mrn, study_num, dtype = parsed
        dicom_dir = find_dicom_directory(item)
        
        if dicom_dir:
            patient_studies[mrn][study_num][dtype] = dicom_dir
    
    # Sort patients by MRN numerically
    sorted_mrns = sorted(patient_studies.keys(), key=int)
    
    # Assign anonymized IDs
    mrn_to_anon_id = {}
    for idx, mrn in enumerate(sorted_mrns, start=1):
        mrn_to_anon_id[mrn] = f"{idx:02d}"
    
    # Write mapping file
    print(f"Writing MRN to anonymized ID mapping to: {MAPPING_OUTPUT}")
    with open(MAPPING_OUTPUT, 'w') as f:
        f.write("MRN\tAnonymized_Patient_ID\n")
        for mrn in sorted_mrns:
            f.write(f"{mrn}\t{mrn_to_anon_id[mrn]}\n")
    
    # Generate shell script
    print(f"Generating anonymization shell script: {SCRIPT_OUTPUT}")
    
    shell_lines = [
        "#!/bin/bash",
        "# Auto-generated script to anonymize DICOM files",
        "# Generated by generate_anonymize_script.py",
        "",
        "set -e  # Exit on error",
        "",
        "# Activate virtual environment",
        "cd /Users/michael/Documents/software/python/dicomrt-anonymize",
        "source .venv/bin/activate",
        "",
        f'OUTPUT_BASE="{OUTPUT_DIR}"',
        "",
        "# Create output directory if it doesn't exist",
        'mkdir -p "$OUTPUT_BASE"',
        "",
    ]
    
    # Track statistics
    total_studies = 0
    skipped = []
    
    for mrn in sorted_mrns:
        anon_id = mrn_to_anon_id[mrn]
        studies = patient_studies[mrn]
        
        for study_num in sorted(studies.keys()):
            study_data = studies[study_num]
            
            # Check if we have both images and rtst
            if 'images' not in study_data or 'rtst' not in study_data:
                missing = []
                if 'images' not in study_data:
                    missing.append('images')
                if 'rtst' not in study_data:
                    missing.append('rtst')
                skipped.append(f"{mrn}_study{study_num} (missing: {', '.join(missing)})")
                continue
            
            ct_dir = study_data['images']
            rtst_dir = study_data['rtst']
            
            # Output directories
            ct_output = f"$OUTPUT_BASE/{anon_id}_study{study_num}_ctslices"
            rtst_output = f"$OUTPUT_BASE/{anon_id}_study{study_num}_rtstructureset"
            
            # We need to work around anonymize.py's fixed output structure
            # It creates ct_slices/ and rt_structure_set/ subdirs
            # So we'll use a temp output dir and then move the contents
            temp_output = f"$OUTPUT_BASE/temp_{anon_id}_study{study_num}"
            
            shell_lines.append(f"# Patient {anon_id}, Study {study_num} (MRN: {mrn})")
            shell_lines.append(f'echo "Processing patient {anon_id}, study {study_num}..."')
            shell_lines.append(f'python anonymize.py \\')
            shell_lines.append(f'  --ct-dir "{ct_dir}" \\')
            shell_lines.append(f'  --rtstruct-dir "{rtst_dir}" \\')
            shell_lines.append(f'  --output-dir "{temp_output}" \\')
            shell_lines.append(f'  --patient-name "ANON_{anon_id}" \\')
            shell_lines.append(f'  --patient-id "{anon_id}"')
            shell_lines.append(f"")
            shell_lines.append(f"# Move outputs to final locations")
            shell_lines.append(f'mv "{temp_output}/ct_slices" "{ct_output}"')
            shell_lines.append(f'mv "{temp_output}/rt_structure_set" "{rtst_output}"')
            shell_lines.append(f'rmdir "{temp_output}"')
            shell_lines.append(f"")
            
            total_studies += 1
    
    shell_lines.append('echo ""')
    shell_lines.append('echo "=========================================="')
    shell_lines.append(f'echo "Anonymization complete! Processed {total_studies} patient-studies."')
    shell_lines.append('echo "=========================================="')
    
    # Write shell script
    with open(SCRIPT_OUTPUT, 'w') as f:
        f.write('\n'.join(shell_lines))
    
    # Make executable
    os.chmod(SCRIPT_OUTPUT, 0o755)
    
    # Print summary
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    print(f"Total patients: {len(sorted_mrns)}")
    print(f"Total patient-studies to process: {total_studies}")
    
    if skipped:
        print(f"\nSkipped {len(skipped)} patient-studies due to missing data:")
        for s in skipped:
            print(f"  - {s}")
    
    print(f"\nOutput files:")
    print(f"  - Shell script: {SCRIPT_OUTPUT}")
    print(f"  - MRN mapping: {MAPPING_OUTPUT}")
    print(f"\nTo run the anonymization, execute:")
    print(f"  bash {SCRIPT_OUTPUT}")


if __name__ == "__main__":
    main()
